language: ruby
sudo: false

rvm:
  - "2.4.1"
  - "2.3.4"
  - "2.2.7"

install:
  - bundle install --retry=3

env:
  - ACTIVE_RECORD_BRANCH="master"
  - ACTIVE_RECORD_BRANCH="5-1-stable"
  - ACTIVE_RECORD_BRANCH="5-0-stable"
  - ACTIVE_RECORD_VERSION="~> 5.1.0"
  - ACTIVE_RECORD_VERSION="~> 5.0.0"

matrix:
  allow_failures:
    - env: ACTIVE_RECORD_BRANCH="master"
    - env: ACTIVE_RECORD_BRANCH="5-1-stable"
    - env: ACTIVE_RECORD_BRANCH="5-0-stable"
